///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Copyright 2007 David Martin. All Rights Reserved.
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#define ID_STATUS_BAR	(WM_APP + 77)
#define KAVI_TRAY_MESSAGE	(WM_APP + 78)
//Menu Items
#define IDM_APP_EXIT					(WM_APP + 101)
#define IDM_SYS_APP_SHOW				(WM_APP + 102)
#define IDM_SYS_APP_HIDE				(WM_APP + 103)
#define IDM_APP_STARTUP					(WM_APP + 105)
#define IDM_SYS_VISUAL_IPCONFIG			(WM_APP + 106)
#define IDM_SYS_EDIT_REMINDER			(WM_APP + 107)
#define IDM_SYS_DEL_REMINDER			(WM_APP + 108)
#define IDM_SYS_DELETE_ALL_REMINDER		(WM_APP + 109)
#define IDC_host_name					(WM_APP + 110)
#define IDC_dns_server					(WM_APP + 111)
#define IDC_node_type					(WM_APP + 112)
#define IDC_net_bios					(WM_APP + 113)
#define IDC_adapter						(WM_APP + 114)
#define IDC_adapter_addess				(WM_APP + 115)
#define IDC_ip_address					(WM_APP + 116)
#define IDC_subnetmask					(WM_APP + 117)
#define IDC_default_gateway				(WM_APP + 118)
#define IDC_type						(WM_APP + 119)
#define IDC_dhcp_server					(WM_APP + 120)
#define IDC_primary_wins				(WM_APP + 121)
#define IDC_secondary_wins				(WM_APP + 122)
#define IDC_lease_obtained				(WM_APP + 123)
#define IDC_lease_expires				(WM_APP + 124)
//#define IDD_DIALOG2					(WM_APP + 110)

#define IDI_ICON                        (WM_APP + 125)
#define IDB_BUTTON						(WM_APP + 126)
#define IDB_BUTTON1		                (WM_APP + 127)
#define TIMER_ID60_SEC	                (WM_APP + 128)
#define IDB_BUTTON2		                (WM_APP + 129)
#define IDB_BUTTON3		                (WM_APP + 130)
#define IDC_STATIC_TEXT                 (WM_APP + 131)
#define IDC_Release                     (WM_APP + 132)
#define IDC_Renew						(WM_APP + 133)
#define IDM_Anchor						(WM_APP + 134)
#define TIMER_ID60_SEC	                (WM_APP + 135)
#define IDM_options						(WM_APP + 136)
#define IDM_Release						(WM_APP + 137)
#define IDM_Renew						(WM_APP + 138)
#define IDM_TASK						(WM_APP + 139)

